services:
  - type: web
    name: epicspace-backend
    env: java
    buildCommand: "chmod +x mvnw && ./mvnw clean install -DskipTests"
    startCommand: "java -jar target/CapstoneBackend-0.0.1-SNAPSHOT.jar"
    region: frankfurt
    rootDir: BACKEND
    envVars:
      - key: java_version
        value: 17
      - key: spring.datasource.password
        value: sql1234
      - key: cloudinary.name
        value: dwrcew77d
      - key: cloudinary.apikey
        value: 124875963796878
      - key: cloudinary.secret
        value: laCTGdd2LF8l5L4XjJzqVsKiAck
      - key: jwt.secret
        value: ciaociaociaociaociaociaociaociao
      - key: gmail.mai.from.password
        value: klnk qwbv zkha lkhh
      - key: gmail.mail.from
        value: ifrimalexandru27@gmail.com
      - key: client-id
        value: ${client-id}
      - key: client-secret
        value: ${client-secret}
      - key: STRIPE_KEY
        value: sk_test_51PUd3wK77lkHwPqgvsmQ2iNwuHmuN8DaKHkIqynNa7IsFRl4GgNQtFUil7aWCN7PmbsbCSTwZ1YkvEKdJDfqaHBc00vh7Bvh3A
