services:
  - type: web
    name: epicspace-backend
    env: java
    buildCommand: "chmod +x mvnw && ./mvnw clean install -DskipTests"
    startCommand: "java -jar target/CapstoneBackend-0.0.1-SNAPSHOT.jar"
    region: frankfurt
    rootDir: BACKEND
    envVars:
      - key: java_version
        value: 17
      - key: spring_datasource_password
        value: sql1234
      - key: cloudinary_name
        value: dwrcew77d
      - key: cloudinary_apikey
        value: 124875963796878
      - key: cloudinary_secret
        value: laCTGdd2LF8l5L4XjJzqVsKiAck
      - key: jwt.secret
        value: ${jwt.secret}
      - key: gmail_mail_from_password
        value: klnk qwbv zkha lkhh
      - key: gmail_mail_from
        value: ifrimalexandru27@gmail.com
      - key: client_id
        value: ${client_id}
      - key: client_secret
        value: ${client_secret}
      - key: stripe_key
        value: sk_test_51PUd3wK77lkHwPqgvsmQ2iNwuHmuN8DaKHkIqynNa7IsFRl4GgNQtFUil7aWCN7PmbsbCSTwZ1YkvEKdJDfqaHBc00vh7Bvh3A
